### ISSUE TITLE
Задание 2 - Vagrant

### ISSUE THREAD

**Issue by romasks** [romasks/flashcards#2]
1. Установи и настрой Vagrant: разверни внутри него Centos 7.1 или Fedora 23
2. Используя Vagrant shell provisioner настрой внутри этой виртуалки всё, что нужно для твоего приложения: ruby, PostgreSQL, git и т.п.
3. Запусти учебное приложение внутри Vagrant-коробки, используя synced folders
4. Добавь в приложение коммит с нужным Vagrantfile

**Comment by romasks** [comment]
Пункт 1 - DONE
Пункт 2 - IN PROGRESS

**Comment by romasks** [comment]
Пункт 2 - DONE
Пункт 3 - IN PROGRESS

**Comment by romasks** [comment]
DONE

**Comment by romasks** [comment]
CHECKING BY MENTOR

**Comment by romasks** [comment]
Заново!

**Comment by romasks** [comment]
План таков:
1) Качаю образ bento/centos-7.1
2) Подключаю chef_solo и всё ставлю
3) Ставлю приложение
3.5) Проверяю работоспособность приложения
4) Проверяю гемы
5) Пускаю тесты
6) Делаю рефактор коду
7) Проверяю работоспособность

**Comment by romasks** [comment]
Пункт 1-3 сделаны.
Пункт 4 - в процессе.

**Comment by parallel588** [comment]
в приложении используется загрузка изображений, в vagrant нужно добавить установку imagemagick

**Comment by romasks** [comment]
Пункт 2 - проблема с postgresql initdb при повторном запуске chef-а;
- добавить IF в скрипты, чтобы их раскоментить и они повторно не запускались.
Пункт 3 - ...
Пункт 3.5 - приложение запущено.
Пункт 4 - rails обновлен до 4.2.5.1, также обновлены некоторые гемы.

**Comment by romasks** [comment]
Пункт 5 - все тесты проходят на зелёненько!

**Comment by romasks** [comment]
Остался рефакторинг кода!

**Comment by romasks** [comment]
Сделан вместе с первым заданием.
На потом - пересмотреть рефакторинг кода.
